# Generated by Django 6.0.5 on 2026-06-12 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smallstack', '0008_apitoken_type_and_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_key', models.CharField(blank=True, default='', max_length=128)),
                ('redirect_uri', models.URLField()),
                ('code_challenge', models.CharField(max_length=128)),
                ('code_challenge_method', models.CharField(default='S256', max_length=10)),
                ('scope', models.CharField(blank=True, default='', max_length=200)),
                ('client_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('api_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_oauth_codes', to='smallstack.apitoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_oauth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
