# Generated by Django 6.0.2 on 2026-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_add_api_token_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="request_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
