# Generated by Django 6.0.7 on 2026-07-19 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('job_kind', models.CharField(choices=[('task', 'Task'), ('command', 'Management command'), ('agent', 'AI agent')], default='task', max_length=16)),
                ('task_path', models.CharField(max_length=300)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('queue_name', models.CharField(default='default', max_length=64)),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('interval', 'Interval'), ('cron', 'Cron')], max_length=10)),
                ('interval_spec', models.CharField(blank=True, max_length=20)),
                ('anchor_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('allow_overlap', models.BooleanField(default=False, help_text='If off, skip a fire while the previous run is still unfinished.')),
                ('catch_up', models.CharField(choices=[('run_once', 'Run once, then resume'), ('skip', 'Skip missed runs')], default='run_once', max_length=10)),
                ('max_retries', models.PositiveSmallIntegerField(default=0, help_text='Reserved (Phase 3).')),
                ('source', models.CharField(choices=[('code', 'Code (@scheduled)'), ('ui', 'UI')], default='ui', max_length=8)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Job',
                'verbose_name_plural': 'Scheduled Jobs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('skipped', 'Skipped'), ('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_result_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduler.scheduledjob')),
            ],
            options={
                'verbose_name': 'Scheduled Job Run',
                'verbose_name_plural': 'Scheduled Job Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='scheduler_s_job_id_6abeca_idx')],
            },
        ),
    ]
