# Generated by Django 6.0.7 on 2026-07-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='schedule_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
