# Generated by Django 6.1 on 2026-09-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduledjob_schedule_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='auto_retired',
            field=models.BooleanField(default=False, help_text='Disabled automatically because no code spec declared it. Re-enabled automatically if the spec returns.'),
        ),
    ]
