# Generated by Django 6.0.7 on 2026-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('guid', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'collected feed item',
                'ordering': ['-published', '-fetched_at'],
                'indexes': [models.Index(fields=['source', '-published'], name='feeds_colle_source_40567b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'guid'), name='uniq_feed_source_guid')],
            },
        ),
    ]
