# Generated by Django 6.0.5 on 2026-07-01 01:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _split_into_model_b(apps, schema_editor):
    """Split each existing Document version-chain into one logical Document
    (the surviving root row) + a DocumentVersion per chain member.

    Runs while Document still has both the old chain fields (file, is_current,
    previous_version, version, uploaded_by) and the new logical fields
    (runbook, key, current_version, created_by, is_generated).
    """
    from collections import defaultdict

    from django.utils.text import slugify

    Document = apps.get_model("smallstack_runbook", "Document")
    DocumentVersion = apps.get_model("smallstack_runbook", "DocumentVersion")

    all_docs = list(Document.objects.all())
    by_id = {d.id: d for d in all_docs}

    def root_of(d):
        cur = d
        while cur.previous_version_id:
            cur = by_id[cur.previous_version_id]
        return cur

    chains = defaultdict(list)
    for d in all_docs:
        chains[root_of(d).id].append(d)

    used_keys = defaultdict(set)  # runbook_id -> {key}

    for root_id, members in chains.items():
        root = by_id[root_id]
        members_sorted = sorted(members, key=lambda d: d.version)
        head = next((d for d in members if d.is_current), members_sorted[-1])

        runbook_id = root.section.runbook_id if root.section_id else None

        # Derive a stable key from the slug, unique within the runbook.
        base_key = (root.slug or slugify(root.title) or "doc")[:200]
        if runbook_id is not None:
            key = base_key
            n = 2
            while key in used_keys[runbook_id]:
                key = f"{base_key}-{n}"[:200]
                n += 1
            used_keys[runbook_id].add(key)
        else:
            key = None  # no namespace → keyless (pk-addressable only)

        # Backfill identity onto the surviving (root) row.
        root.runbook_id = runbook_id
        root.key = key
        root.is_generated = False
        root.created_by_id = root.uploaded_by_id
        root.via = "web"

        # One DocumentVersion per chain member (content moves off the chain).
        head_version = None
        for d in members_sorted:
            dv = DocumentVersion.objects.create(
                document=root,
                version=d.version,
                file=d.file,
                file_type=d.file_type,
                content_text=d.content_text,
                title=d.title,
                description=d.description,
                via="web",
                created_by_id=d.uploaded_by_id,
            )
            # Preserve the original timestamp (auto_now_add overrides it on create).
            DocumentVersion.objects.filter(pk=dv.pk).update(created_at=d.created_at)
            if d.id == head.id:
                head_version = dv

        # Point the head + refresh denormalised fields.
        root.current_version = head_version
        root.version = head.version
        root.file_type = head.file_type
        root.content_text = head.content_text
        root.save()

        # Drop the non-root version rows (data now lives in DocumentVersion).
        # Images attach to the root only, so nothing cascades away here.
        for d in members_sorted:
            if d.id != root.id:
                d.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack_runbook', '0002_documentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('file', models.FileField(upload_to='runbook/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])])),
                ('file_type', models.CharField(blank=True, choices=[('md', 'Markdown')], editable=False, max_length=10)),
                ('content_text', models.TextField(blank=True, editable=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Per-version note / changelog.')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('via', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='ss_rb_doc_is_curr_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='ss_rb_doc_sec_curr_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbook_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='key',
            field=models.SlugField(blank=True, help_text='Stable handle, unique per runbook.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='max_version_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='max_versions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='on_expire',
            field=models.CharField(choices=[('archive', 'Archive'), ('delete', 'Delete')], default='archive', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='runbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='smallstack_runbook.runbook'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='ttl_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='via',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True, editable=False, help_text='Head plaintext for search.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('md', 'Markdown')], editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbook_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='smallstack_runbook.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smallstack_runbook.documentversion'),
        ),
        # Data migration: split chains into logical Document + DocumentVersion.
        # Runs before the old chain fields are removed below.
        migrations.RunPython(_split_into_model_b, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_archived'], name='ss_rb_doc_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('key__isnull', False)), fields=('runbook', 'key'), name='uniq_runbook_key'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='document',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_document_version'),
        ),
    ]
