# Generated by Django 6.0.5 on 2026-07-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack_runbook', '0003_documentversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runbook',
            name='default_max_version_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runbook',
            name='default_max_versions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runbook',
            name='default_ttl_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
