# Generated by Django 6.0.5 on 2026-07-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack_runbook', '0006_document_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
