# Generated by Django 6.1 on 2026-09-25 01:16

import django.core.validators
from django.db import migrations, models

import apps.runbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack_runbook', '0010_runbook_is_public_runbook_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(upload_to=apps.runbook.models.document_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
    ]
