# Generated by Django 6.0.2 on 2026-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smallstack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuprecord",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("download", "Download"),
                    ("cron", "Cron"),
                    ("command", "Command"),
                    ("system", "System"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
