# Generated by Django 6.0.2 on 2026-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smallstack", "0002_alter_backuprecord_triggered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="pruned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
