# Generated by Django 6.0.2 on 2026-03-10 19:09

from django.db import migrations, models


def remap_trigger_values(apps, schema_editor):
    """Remap old triggered_by values to new ones.

    Old -> New:
      command  -> scheduler  (mgmt command / cron)
      manual   -> command    (Backup Now button)
      download -> manual     (Download button)
      cron     -> scheduler  (legacy)

    Uses temp values to avoid collisions.
    """
    BackupRecord = apps.get_model("smallstack", "BackupRecord")
    # Step 1: move to temp values to avoid collisions
    BackupRecord.objects.filter(triggered_by="command").update(triggered_by="_scheduler")
    BackupRecord.objects.filter(triggered_by="manual").update(triggered_by="_command")
    BackupRecord.objects.filter(triggered_by="download").update(triggered_by="_manual")
    BackupRecord.objects.filter(triggered_by="cron").update(triggered_by="_scheduler2")
    # Step 2: set final values
    BackupRecord.objects.filter(triggered_by="_scheduler").update(triggered_by="scheduler")
    BackupRecord.objects.filter(triggered_by="_command").update(triggered_by="command")
    BackupRecord.objects.filter(triggered_by="_manual").update(triggered_by="manual")
    BackupRecord.objects.filter(triggered_by="_scheduler2").update(triggered_by="scheduler")


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack', '0004_consolidate_pruned_records'),
    ]

    operations = [
        migrations.RunPython(remap_trigger_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='backuprecord',
            name='triggered_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('command', 'Command'), ('scheduler', 'Scheduler'), ('system', 'System')], default='manual', max_length=10),
        ),
    ]
