# Generated by Django 6.0.5 on 2026-06-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack', '0008_apitoken_type_and_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token_type',
            field=models.CharField(choices=[('login', 'Login'), ('manual', 'Manual'), ('oauth', 'OAuth')], default='manual', max_length=10),
        ),
    ]
