# Generated by Django 6.0.2 on 2026-03-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_userprofile_color_palette"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="color_palette",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "System Default"),
                    ("django", "Django"),
                    ("high-contrast", "High Contrast"),
                    ("dark-blue", "Dark Blue"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                ],
                default="",
                help_text="Color palette override (blank = system default)",
                max_length=20,
            ),
        ),
    ]
