# Generated by Django 6.0.2 on 2026-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_userprofile_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, choices=[('', 'Use system default'), ('Americas', [('America/New_York', 'Eastern Time (New York)'), ('America/Chicago', 'Central Time (Chicago)'), ('America/Denver', 'Mountain Time (Denver)'), ('America/Los_Angeles', 'Pacific Time (Los Angeles)'), ('America/Anchorage', 'Alaska (Anchorage)'), ('Pacific/Honolulu', 'Hawaii (Honolulu)'), ('America/Toronto', 'Toronto'), ('America/Vancouver', 'Vancouver'), ('America/Mexico_City', 'Mexico City'), ('America/Sao_Paulo', 'São Paulo'), ('America/Argentina/Buenos_Aires', 'Buenos Aires'), ('America/Bogota', 'Bogotá'), ('America/Lima', 'Lima')]), ('Europe', [('Europe/London', 'London'), ('Europe/Dublin', 'Dublin'), ('Europe/Paris', 'Paris'), ('Europe/Berlin', 'Berlin'), ('Europe/Amsterdam', 'Amsterdam'), ('Europe/Madrid', 'Madrid'), ('Europe/Rome', 'Rome'), ('Europe/Zurich', 'Zurich'), ('Europe/Stockholm', 'Stockholm'), ('Europe/Warsaw', 'Warsaw'), ('Europe/Athens', 'Athens'), ('Europe/Moscow', 'Moscow'), ('Europe/Istanbul', 'Istanbul')]), ('Asia & Pacific', [('Asia/Dubai', 'Dubai'), ('Asia/Kolkata', 'India (Kolkata)'), ('Asia/Shanghai', 'China (Shanghai)'), ('Asia/Tokyo', 'Tokyo'), ('Asia/Seoul', 'Seoul'), ('Asia/Singapore', 'Singapore'), ('Asia/Hong_Kong', 'Hong Kong'), ('Asia/Bangkok', 'Bangkok'), ('Asia/Jakarta', 'Jakarta'), ('Australia/Sydney', 'Sydney'), ('Australia/Melbourne', 'Melbourne'), ('Australia/Perth', 'Perth'), ('Pacific/Auckland', 'Auckland')]), ('Africa & Middle East', [('Africa/Cairo', 'Cairo'), ('Africa/Lagos', 'Lagos'), ('Africa/Johannesburg', 'Johannesburg'), ('Africa/Nairobi', 'Nairobi'), ('Asia/Jerusalem', 'Jerusalem'), ('Asia/Riyadh', 'Riyadh')])], default='', help_text='Your local timezone for displaying dates and times', max_length=50),
        ),
    ]
