# Generated by Django 6.0.7 on 2026-07-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.webhooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_url', models.URLField(help_text='Where signed event POSTs are sent.', max_length=500)),
                ('secret', models.CharField(default=apps.webhooks.models.generate_secret, help_text='Signing key. The receiver verifies X-SmallStack-Signature with it.', max_length=100)),
                ('event_filter', models.JSONField(blank=True, default=list, help_text='Event patterns, e.g. ["scheduler.scheduledjob.*", "*.created"].')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('dead', 'Dead')], max_length=10)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL segment: POSTs arrive at /webhooks/in/<slug>/.', max_length=100, unique=True)),
                ('handler', models.CharField(blank=True, help_text='Registered handler name. Blank ⇒ use the slug.', max_length=100)),
                ('secret', models.CharField(default=apps.webhooks.models.generate_secret, max_length=100)),
                ('signature_header', models.CharField(default='X-Signature', help_text='Request header carrying the HMAC-SHA256 hex digest.', max_length=80)),
                ('require_signature', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_receivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Receiver',
                'verbose_name_plural': 'Webhook Receivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('success', 'Success'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=10)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('task_result_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='webhooks_we_status_afd94b_idx'), models.Index(fields=['endpoint', '-created_at'], name='webhooks_we_endpoin_81c26d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='accepted', max_length=10)),
                ('task_result_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='webhooks.webhookreceiver')),
            ],
            options={
                'verbose_name': 'Webhook Receipt',
                'verbose_name_plural': 'Webhook Receipts',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['receiver', '-received_at'], name='webhooks_we_receive_d9e52e_idx')],
            },
        ),
    ]
