# Generated by Django 6.0.7 on 2026-07-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='auth_scheme',
            field=models.CharField(blank=True, default='hmac', help_text='Outbound auth scheme (@webhook_auth name). Default: hmac (X-SmallStack-Signature).', max_length=64),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='transform',
            field=models.CharField(blank=True, default='smallstack', help_text='Outbound payload transform (@webhook_transform name). Default: smallstack envelope.', max_length=64),
        ),
        migrations.AddField(
            model_name='webhookreceipt',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='webhookreceiver',
            name='challenge',
            field=models.CharField(blank=True, default='', help_text='Inbound challenge/handshake (@webhook_challenge name). Blank: none.', max_length=64),
        ),
        migrations.AddField(
            model_name='webhookreceiver',
            name='ignore_origin',
            field=models.CharField(blank=True, default='', help_text='Drop inbound events whose X-SmallStack-Origin equals this (self-origin loop guard).', max_length=200),
        ),
        migrations.AddField(
            model_name='webhookreceiver',
            name='verifier',
            field=models.CharField(blank=True, default='hmac', help_text='Inbound signature verifier (@webhook_verifier name). Default: hmac (raw-body HMAC).', max_length=64),
        ),
        migrations.AlterField(
            model_name='webhookreceipt',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='accepted', max_length=10),
        ),
    ]
