# Generated by Django 6.0.7 on 2026-07-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookdelivery_event_id_webhookendpoint_auth_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='is_paired',
            field=models.BooleanField(default=False, help_text='Managed by the SmallStack↔SmallStack pairing flow (read-only).'),
        ),
        migrations.AddField(
            model_name='webhookreceiver',
            name='is_paired',
            field=models.BooleanField(default=False, help_text='Managed by the SmallStack↔SmallStack pairing flow (read-only).'),
        ),
    ]
