# Generated by Django 6.1 on 2026-09-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_webhookendpoint_is_paired_webhookreceiver_is_paired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookreceiver',
            name='signature_header',
            field=models.CharField(default='X-SmallStack-Signature', help_text="Request header carrying the HMAC-SHA256 hex digest. Matched case-insensitively. Default matches SmallStack's own sender; set e.g. 'X-Signature' or 'X-Hub-Signature-256' for a third party.", max_length=80),
        ),
    ]
