# Generated by Django 6.0.2 on 2026-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Heartbeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("status", models.CharField(choices=[("ok", "OK"), ("fail", "Fail")], max_length=10)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
    ]
