# Generated by Django 6.0.2 on 2026-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0002_heartbeatepoch'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('expected_count', models.PositiveIntegerField(default=0)),
                ('avg_response_ms', models.PositiveIntegerField(default=0)),
                ('uptime_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Daily Summary',
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='heartbeatepoch',
            name='service_minimum',
            field=models.DecimalField(decimal_places=2, default=99.5, help_text='SLA minimum uptime % (threshold for public status)', max_digits=5),
        ),
        migrations.AddField(
            model_name='heartbeatepoch',
            name='service_target',
            field=models.DecimalField(decimal_places=2, default=99.9, help_text='SLA target uptime % (goal for internal tracking)', max_digits=5),
        ),
    ]
