# Generated by Django 6.0.2 on 2026-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heartbeat", "0003_heartbeatdaily_heartbeatepoch_service_minimum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heartbeat",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
