# Generated by Django 6.0.5 on 2026-05-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0005_maintenancewindow_heartbeat_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeatepoch',
            options={'ordering': ['-started_at'], 'verbose_name': 'Heartbeat Epoch', 'verbose_name_plural': 'Heartbeat Epoch'},
        ),
    ]
