# Generated by Django 6.0.5 on 2026-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0006_alter_heartbeatepoch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeatepoch',
            options={'ordering': ['-started_at'], 'verbose_name': 'Heartbeat Epoch', 'verbose_name_plural': 'Heartbeat Epochs'},
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='monitor_key',
            field=models.SlugField(default='site'),
        ),
        migrations.AddField(
            model_name='heartbeatdaily',
            name='monitor_key',
            field=models.SlugField(default='site'),
        ),
        migrations.AddField(
            model_name='heartbeatepoch',
            name='monitor_key',
            field=models.SlugField(default='site'),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='monitor_key',
            field=models.SlugField(default='site'),
        ),
        migrations.AlterField(
            model_name='heartbeatdaily',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['monitor_key', 'timestamp'], name='heartbeat_monitor_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='heartbeatdaily',
            constraint=models.UniqueConstraint(fields=('monitor_key', 'date'), name='unique_daily_per_monitor'),
        ),
        migrations.AddConstraint(
            model_name='heartbeatepoch',
            constraint=models.UniqueConstraint(fields=('monitor_key',), name='unique_epoch_per_monitor'),
        ),
    ]
