# Generated by Django 6.0.5 on 2026-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0007_alter_heartbeatepoch_options_heartbeat_monitor_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Stable identifier; forms the monitor key.', unique=True)),
                ('service', models.SlugField(default='custom', help_text='Which service this monitor relates to: site, api, mcp, search, or custom.')),
                ('url', models.URLField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST')], default='GET', max_length=8)),
                ('expected_status', models.PositiveIntegerField(default=200, help_text='HTTP status that counts as up.')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False, help_text='Show on the public status page?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitored Endpoint',
                'verbose_name_plural': 'Monitored Endpoints',
                'ordering': ['name'],
            },
        ),
    ]
