# Generated by Django 6.0.5 on 2026-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0008_monitoredendpoint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='heartbeat',
            name='heartbeat_monitor_ts_idx',
        ),
        migrations.AddConstraint(
            model_name='heartbeat',
            constraint=models.UniqueConstraint(fields=('monitor_key', 'timestamp'), name='unique_beat_per_monitor_minute'),
        ),
    ]
