# Generated by Django 6.0.5 on 2026-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0009_remove_heartbeat_heartbeat_monitor_ts_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredendpoint',
            name='public',
            field=models.BooleanField(default=False, help_text='Mark this monitor as public (intended for the public status board).'),
        ),
    ]
