# Generated by Django 6.0.5 on 2026-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0010_alter_monitoredendpoint_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('api', 'API endpoint'), ('mcp', 'MCP tool')], max_length=8)),
                ('target', models.CharField(help_text="The exposed surface's identifier (REST registry name or MCP tool name).", max_length=200)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Stable identifier; forms the monitor key.', unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False, help_text='Mark this monitor as public (intended for the public status board).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Monitor',
                'verbose_name_plural': 'Site Monitors',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'target'), name='unique_surface_per_target')],
            },
        ),
    ]
