# Generated by Django 6.1 on 2026-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogCaptureWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[("DEBUG", "Debug"), ("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        default="DEBUG",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("started_by", models.CharField(blank=True, default="", max_length=150)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "log capture window",
                "verbose_name_plural": "log capture windows",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField(db_index=True)),
                ("level", models.CharField(max_length=10)),
                ("level_no", models.PositiveSmallIntegerField(db_index=True)),
                ("logger", models.CharField(db_index=True, max_length=200)),
                ("message", models.TextField()),
                ("module", models.CharField(blank=True, default="", max_length=200)),
                ("func", models.CharField(blank=True, default="", max_length=200)),
                ("line", models.PositiveIntegerField(default=0)),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("trace_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("exc_type", models.CharField(blank=True, default="", max_length=200)),
                ("exc_text", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "log record",
                "verbose_name_plural": "log records",
                "ordering": ["-ts", "-pk"],
                "indexes": [models.Index(fields=["-ts", "level_no"], name="telemetry_ts_level_idx")],
            },
        ),
    ]
