# Generated by Django 6.1 on 2026-09-26 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallstack_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subject_key', 'read_at'], name='notif_subject_unread'),
        ),
    ]
